AS cancelation is not interrupting consumer anymore
gridsuite/security-analysis-server pull request #91
Opened 2023-10-31 13:09 UTC by archendel

2023-11-02 14:03 UTC, AAJELLAL approved these changes
Code and tests are ok.

2023-11-03 12:34 UTC, Tristan-WorkGH requested changes

2023-11-03 12:35 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/securityanalysis/server/util/SecurityAnalysisException.java
> +        COMPUTATION_RUN_ERROR
The default case with "500 Internal server error" is sufficient.

2023-11-03 14:18 UTC, flomillot commented
As discussed with @etiennehomer , the version copied on SCA : https://github.com/gridsuite/security-analysis-server/pull/92

2023-11-06 10:50 UTC, closed without merging