Log not found equipment
gridsuite/security-analysis-server pull request #98
Opened 2023-12-06 08:32 UTC by YenguiSeddik

2023-12-07 13:00 UTC, FranckLecuyer requested changes

2023-12-07 13:02 UTC, FranckLecuyer requested changes
Tests: NullPointerException on a n-1 contingency with an equipment id not found

2023-12-08 13:52 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/securityanalysis/server/service/SecurityAnalysisWorkerService.java
> +                    notFE.put(contingencyInfos.getContingency().getId(), elementsIds);
Done

2023-12-08 13:52 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/securityanalysis/server/service/SecurityAnalysisWorkerService.java
> +                elementNotFoundSubReporter.report(Report.builder()
Removed

2023-12-11 09:08 UTC, FranckLecuyer approved these changes
Code review: OK
Tests: OK

2023-12-12 11:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/securityanalysis/server/service/SecurityAnalysisWorkerService.java
> +        List<Report> notFoundElementReports = new ArrayList<>();
You can move this to row 235

2023-12-13 12:48 UTC, etiennehomer commented on src/main/java/org/gridsuite/securityanalysis/server/service/SecurityAnalysisWorkerService.java
> +                        .collect(Collectors.toList()),
.filter(Objects::nonNull)
                        .toList())

2023-12-13 12:49 UTC, etiennehomer approved these changes

2023-12-14 14:08 UTC, merged